# Generated by Django 3.1.2 on 2020-10-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='date_issue',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='note',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
