# Generated by Django 3.1.2 on 2020-10-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201003_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
