# Generated by Django 3.1.2 on 2020-10-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201019_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='ptp',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
