# Generated by Django 3.1.2 on 2020-10-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201019_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
