# Generated by Django 3.1.2 on 2020-10-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='past_due',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='past_due_hor',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
